### ISSUE TITLE
sanic.exceptions.URLBuildError: Endpoint with name `auth.login` was not found

### ISSUE THREAD

**Issue by stopspazzing** [pyx/sanic-auth#2]
```
2017-06-01 16:56:42 - (sanic)[ERROR]: Exception occurred while handling uri: "http://127.0.0.1:8000/setup"
Traceback (most recent call last):
  File "/home/test/sanic/lib/python3.6/site-packages/sanic/app.py", line 471, in handle_request
    response = await response
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 109, in __next__
    return self.gen.send(None)
  File "/home/test/PycharmProjects/Sanic-MDL-Blog/app/views.py", line 104, in setup
    auth.login_user(request, wform.username.data)
  File "/home/test/sanic/lib/python3.6/site-packages/sanic_auth/__init__.py", line 47, in login_user
    self.get_session(request)[self.auth_session_key] = self.serialize(user)
  File "/home/test/sanic/lib/python3.6/site-packages/sanic_auth/__init__.py", line 102, in serialize
    return {'uid': user.id, 'name': user.name}
AttributeError: 'str' object has no attribute 'id'
```

and

```
2017-06-01 17:10:17 - (sanic)[ERROR]: Traceback (most recent call last):
  File "/home/test/sanic/lib/python3.6/site-packages/sanic/app.py", line 471, in handle_request
    response = await response
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 109, in __next__
    return self.gen.send(None)
  File "/home/test/sanic/lib/python3.6/site-packages/sanic_auth/__init__.py", line 87, in privileged
    u = self.login_url or request.app.url_for(self.login_endpoint)
  File "/home/test/sanic/lib/python3.6/site-packages/sanic/app.py", line 357, in url_for
    view_name))
sanic.exceptions.URLBuildError: Endpoint with name `auth.login` was not found
```

**Comment by pyx** [comment]
For the first exception, the default implementation expects a user object with two attributes `user.id` and `user.name`, if you want to use anything without these, you can provide your custom serialize function and user loading function, like so:
```python
auth = Auth(app)

@auth.serializer
def serialize(username):
    return username  # because you are using a string here[1] as the user token

@auth.user_loader
def load_user(name):
    user = # look up user info by 'name' from database
    return user
```

[1] https://github.com/stopspazzing/Sanic-MDL-Blog/blob/b3729140e65366c8e144256a3578e5cb1d3bb905/app/views.py#L164

`serialize` function turns the user object into a token to be saved into login session, this token should be able to identify the user uniquely.  The default 

`load_user` function expects a token that is compatible with the return value of `serialize`, and should return a user object (or whatever your code expects) which identified by the token.

**Comment by pyx** [comment]
Regarding the second exception, by default, Sanic-Auth will redirect unauthorized access to an endpoint named `auth.login`, that's what we usually have if we use a blueprint to group together all auth+auth views, if you are using anything else, you can change the setting accordingly, e.g, in your case:
```python
app.config.AUTH_LOGIN_ENDPOINT = 'login'
```

**Comment by stopspazzing** [comment]
I had the auth_login_endpoint added to config on server start:
https://github.com/stopspazzing/Sanic-MDL-Blog/blob/master/app/views.py#L35

So why would the issue be there if its set properly? Is there something I a missing?

**Comment by pyx** [comment]
The `AUTH_LOGIN_ENDPOINT` value is cached when the `Auth` object is bound to an app, change `AUTH_LOGIN_ENDPOINT` after calling `Auth.setup` has no effect.  `Auth.setup` will be called if an application is passed in when you create the `auth` object (like, in your case).

Caching the value of `AUTH_LOGIN_ENDPOINT` is to avoid reading configuration on each request.

In your code, setting the option (in listener) happen after `auth = Auth(app)` call, which is in module level (import time), so it does not work, and default value of `auth.login` is used instead.

You have many ways to fix it.

1. setup the `Auth` object in the listener, like so,
```python
auth = Auth()

@app.listener('before_server_start')
async def setup_cfg(app, loop):
    ...
    config['AUTH_LOGIN_ENDPOINT'] = 'login'
    ...
    auth.setup(app)
    ...
```

2. change the endpoint attribute directly
```python
@app.listener('before_server_start')
async def setup_cfg(app, loop):
    ...
    auth.login_endpoint = 'login'
    ...
```

3. setting configuration outside of your web app logic
```python
app = Auth(__name__)
...
app.from_file('/path/to/config_file')
...
app = Auth(app)
...
```

Number 3 is the preferred way to handle configurations in Sanic [1], Flask and Bottle.

[1] http://sanic.readthedocs.io/en/latest/sanic/config.html#loading-configuration

**Comment by stopspazzing** [comment]
Resolved issue, thanks for your help.
