### ISSUE TITLE
AttributeError: 'list' object has no attribute 'ctx'

### ISSUE THREAD

**Issue by beliboba** [pyx/sanic-auth#21]
[2022-04-25 15:58:52 +0300] [8448] [ERROR] Exception occurred while handling uri: 'http://127.0.0.1:5000/login'
Traceback (most recent call last):
  File "handle_request", line 83, in handle_request
    )
  File "C:\Users\Beliboba\PycharmProjects\beliboba\main.py", line 64, in login
    auth.login_user(request, user=user)
  File "C:\Users\Beliboba\PycharmProjects\beliboba\venv\lib\site-packages\sanic_auth\__init__.py", line 47, in login_user
    self.get_session(request)[self.auth_session_key] = self.serialize(user)
  File "C:\Users\Beliboba\PycharmProjects\beliboba\venv\lib\site-packages\sanic_auth\__init__.py", line 143, in get_session
    return request.ctx.session
AttributeError: 'list' object has no attribute 'ctx'

**Comment by beliboba** [comment]
Added middleware but i dont know what actually i need to do with it
![image](https://user-images.githubusercontent.com/73661136/166239138-d95096b4-3d64-415f-827c-646481711392.png)
Now it gives me following error:
![image](https://user-images.githubusercontent.com/73661136/166239202-1fb9dacc-7261-4cea-964e-b48abedc0377.png)

**Comment by pyx** [comment]
Are you running the example code? Sanic changed where the context object is located, please install the latest Sanic-Auth and use the latest example in this repository, if the problem persists, please let me know.

**Comment by beliboba** [comment]
hi! I dont remember anything now, thanks for answer btw 😏
